/* This file is automatically generated. Edits will be lost.*/
<<<<<<< HEAD
const int buildversion = 132;
=======
const int buildversion = 135;
>>>>>>> c4625ce2632c123e79a67d91d75b21330e1febb8
const char buildconfig[] = "TEST_NOVAVM";
